xxx = Buffer.o Channel.o Condition.o CountDownLatch.o \
	  CurrentThread.o Date.o EPollPoller.o EventLoop.o \
	  EventLoopThread.o EventLoopThreadPool.o Exception.o \
	  FileUtil.o InetAddress.o Logging.o LogStream.o Poller.o \
	  ProcessInfo.o Socket.o SocketOps.o Thread.o \
	  ThreadPool.o Timer.o TimerQueue.o TimeStamp.o \
	  TimeZone.o
all : ${xxx}

Buffer.o : Buffer.cc
	g++ -c -g Buffer.cc

Channel.o : Channel.cc
	g++ -c Channel.cc

Condition.o : Condition.cc
	g++ -c Condition.cc

CountDownLatch.o : CountDownLatch.cc
	g++ -c CountDownLatch.cc

CurrentThread.o : CurrentThread.cc
	g++ -c CurrentThread.cc

Date.o : Date.cc
	g++ -c Date.cc

EPollPoller.o : EPollPoller.cc
	g++ -c EPollPoller.cc

EventLoop.o : EventLoop.cc
	g++ -c EventLoop.cc

EventLoopThread.o : EventLoopThread.cc
	g++ -c EventLoopThread.cc

EventLoopThreadPool.o : EventLoopThreadPool.cc
	g++ -c EventLoopThreadPool.cc

Exception.o : Exception.cc
	g++ -c Exception.cc

FileUtil.o : FileUtil.cc
	g++ -c FileUtil.cc

InetAddress.o : InetAddress.cc
	g++ -c InetAddress.cc

Logging.o : Logging.cc
	g++ -c Logging.cc

LogStream.o : LogStream.cc
	g++ -c LogStream.cc

Poller.o : Poller.cc
	g++ -c Poller.cc

ProcessInfo.o : ProcessInfo.cc
	g++ -c ProcessInfo.cc

Socket.o : Socket.cc
	g++ -c Socket.cc

SocketOps.o : SocketOps.cc
	g++ -c SocketOps.cc

Thread.o : Thread.cc
	g++ -c Thread.cc

ThreadPool.o : ThreadPool.cc
	g++ -c ThreadPool.cc

Timer.o : Timer.cc
	g++ -c Timer.cc

TimerQueue.o : TimerQueue.cc
	g++ -c TimerQueue.cc

TimeStamp.o : TimeStamp.cc
	g++ -c TimeStamp.cc

TimeZone.o : TimeZone.cc
	g++ -c TimeZone.cc
