#ifndef GLOBAL_HEADER_H
#define GLOBAL_HEADER_H
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <malloc.h>
#include <iostream>
#include <bitset>
#include <time.h>
#include <functional>
#include <iostream>
#include <memory>
#include <string>
#include <math.h>
#include <vector>
#include <functional>
#include <exception>

#include <QObject>
#include <QWidget>
#include <QPoint>
#include <QPainter>
#include <QPen>
#include <QImage>
#include <QFile>
#include <QDir>
#include <QApplication>
#include <QLayout>
#include <QStackedLayout>
#include <QMainWindow>
#include <QStandardItemModel>
#include <QDebug>
#include <QMap>
#include <QThread>
#include <QSemaphore>
#include <QMutex>
#include <QMutexLocker>
#include <QDialog>

#endif // HEADER_H
